### ISSUE TITLE
Problem with quotes on generated img elements

### ISSUE THREAD

**Issue by Richard-Linsdale** [madflow/flow-netbeans-markdown#56] opened 2014-07-03 22:58 UTC
markdown of form

```
![word word word](image.jpg)

![oneword](image.jpg)
```

generates html with incorrect quotes (too many in trailing position of alt attribute)

```
<p><img src="image.jpg" alt="word word word""/></p><p><img src="image.jpg" alt="oneword""/></p>
```

**Comment by Richard-Linsdale** [comment] 2014-07-03 23:24
Just looked at pegdown issues and it seems this is a bug which was introduced in 1.4.2, but is now fixed

see  pegdown issue 130  -- Invalid HTML when serializing images 

looks like you will have to pull a later version of pegdown

**Comment by madflow** [comment] 2014-07-06 12:29
Hi,

yep - there is a regression in the latest development code! There is a pull request for this in pegdown (https://github.com/sirthias/pegdown/pull/133) which has not been merged yet. 

We always use the latest packaged release of pegdown - so we will be patient and wait for the next release with this pull request merged.

If you want to hack on the latest development code of netbeans-markdown - things can break like this from time to time.

If you would simply like Markdown Support in NetBeans - The pre-compiled releases are your best bet:

https://github.com/madflow/flow-netbeans-markdown/releases

Thanks for your interest in this plugin!

**Comment by madflow** [comment] 2014-07-07 10:04
Okay - It turns out we override the image tag rendering after all in the plugin... 

I tested the fix with this commit https://github.com/madflow/flow-netbeans-markdown/commit/88aaafc656f6c3fc5919914f5e3fbc98d7319b64 and it looks better (to say the least),

I witnessed some occasional NullPointerException (not sure if it is related).

Maybe you can have a quick test on your side?

**Comment by Richard-Linsdale** [comment] 2014-07-07 20:08
Using your latest N8 branch my markdown generation still failed with the same problem code generated.

your commit made a minor typographic change to the existing printImageTag (space added between closing quote and closing ">") and you introduced an additional printImageTag method with an alternative signature (which was defined with an @Override directive.)

I ran my simple test case (see the info in the first posting for this issue) in debug  mode, and neither printImageTag methods where called when the html was generated.  I have to assume that the pegdown method for image tag creation is used and hence the bug in 1.4.2 is being seen in your plug-in's html generation.

Hope this is helpful.

/Richard

**Comment by madflow** [comment] 2014-07-07 20:51
Thanks for the test. Yes it helped. I believe I was investigating in the wrong place. You wrote "generates html" and I thought you meant the html preview.

The preview did call the newly created method - the export did not. I took a second shot at the issue by just adapting the "preview" code. With my setup (NetBeans 8, JDK 8, Linux) the export now produces a valid image tag - but it is a hack.

**Comment by Richard-Linsdale** [comment] 2014-07-11 22:01
The quoting problem seems to be resolved - however the src attribute is expanded into an absolute file path and so the resulting code is not transportable to servers etc.  Given that the attribute value is defined in the md text (can be either a relative or absolute file path) I would have hoped that the attribute value would be copied as-is into the resulting img element.

```
![word word word](image.jpg)
```

results in

```
<img src="file:/home/richard/GitHubProjects/debugging/image.jpg" alt="word word word" />
```

where as I would have hoped it would result in

```
<img src="image.jpg" alt="word word word" />
```

_tested on the same environment as you are using ie NetBeans 8, JDK 8, Linux._

**Comment by madflow** [comment] 2014-07-13 09:53
I reverted the premature fix from above and introduced a custom HTML export/generation class for the export feature.

The last commit https://github.com/madflow/flow-netbeans-markdown/commit/f3cd809e94710398a7e2d1171a2f0705cf085e2d fixes the issues above. I will do some more testing in the next couple of days if I have missed something.

**Comment by Richard-Linsdale** [comment] 2014-07-13 22:14
Looks good for "Generate HTML".
"View HTML" still generates absolute file paths - but that's not a problem as view will work and does not create long-lived output. However just to be tidy, it would be good if both View and Generate created the same output.

**Comment by stengerh** [comment] 2014-07-14 08:41
It might be tidy but it comes with other drawbacks. The reason I introduced absolute image URLs in the preview HTML was to enable the correct display of images. Since the preview HTML gets written to a temporary file relative paths wouldn't work. I also didn't want to write the preview HTML to the same directory as the Markdown file as that might have broken existing workflows. The assumption here is that (most) people use the preview functionality as a visual preview and not as a preview of the HTML source code.

**Comment by Richard-Linsdale** [comment] 2014-07-14 13:40
good point -  I accept that further changes to "view HTML" is not good. So commit `f3cd809` seems to be the fix for this issue (unless someone notices something that I haven't).

**Closed as completed** 2014-08-27 10:39 UTC
Labels: Bug
