### ISSUE TITLE
Problems in accented characters

### ISSUE THREAD

**Issue by fredw** [madflow/flow-netbeans-markdown#20] opened 2013-07-25 19:37 UTC
Hi,

When used accented characters (ã, é, ó, etc) in the text, the generated HTML displays � in place.
The solution would be respectively convert them to html entities: <code>&atilde ;, &eacute ;, &oacute ;</code>

Thanks in advance.

**Comment by madflow** [comment] 2013-07-26 09:02
Hello,

this sounds like an encoding issue of your files. Accented characters work fine here and have not been reported as a specific for this plugin yet.

The plugin uses the same character encoding like the NetBeans default: UTF-8 . You can specifically define the HTML charset under Options->Miscellaneous->Markdown->HTML Export (This does not affect the file encoding - only the HTML meta-header!).

I can reproduce your issue when saving a file in latin-1 moving it to a NetBeans project. Then the "VIew HTML" displays the b0rked HTML  - which is "correct" since my project encoding is set to UTF-8.

In order to further debug this - please state your 
- Operating System
- NetBeans Version
- Browser
- Project Encoding (The project you are working on)
- File Encoding of the markdown file
- Whether you are trying to preview an alien file outside of you project, or if you have typed the Markdown content and then try to preview it.

Thanks

**Comment by fredw** [comment] 2013-07-26 13:06
I already have custom in dealing with this kind of problem encode. Before posting the problem I checked all the possibilities.
1. In Netbeans my files are always edited/created in UTF-8. Anyway, to make sure, I opened with Notepad++ and the file is saved as UTF-8 without BOM;
2. My version of Netbeans is 7.3;
3. To get around the problem had to set the encode as iso-8859-1. But I think is not the right way, because currently I schedule all using UTF-8 and never had this kind of problem;
4. The project is in UTF-8. There is little wonder that when I edit a different file that I encode your own newly Netbeans alerts;
5. Currently and unfortunately my current system is Windows 8 + 64bit.

Thanks!

**Comment by madflow** [comment] 2013-07-26 20:15
Can you confirm that the problem occurs in the File-Menu Action (Right Click on file) and/or the Editor-Context Action (Click on Icon in editor window)?

![bildschirmfoto vom 2013-07-26 22 07 32](https://f.cloud.github.com/assets/183248/865058/a500776a-f62f-11e2-9be9-c81beabea4e6.png)

Optionally converting all special characters to their HTML entities is a hack. I would rather fix the real problem - If I can do anything about it in the boundaries of this plugin.

**Comment by fredw** [comment] 2013-07-26 20:25
The problem occurs with both options.

**Comment by fredw** [comment] 2013-07-26 20:31
For the tests I did, saving the file in a html it does not encode the problem occurs.
The problem only occurs with the option "View HTML".

**Comment by junichi11** [comment] 2013-07-27 01:59
I'm sorry, there is a problem with the part of the source code that have been added by me.
Perhaps this problem will be occurred in Windows.

A temporary workaround is the following:
add `-J-Dfile.encoding=UTF-8` to netbeans_default_options in netbeans.conf

@madflow 
I debugged it. 
The text encoding is default system encoding when we get it from document object.
I'll try to fix it.

Thanks.

**Comment by madflow** [comment] 2013-07-27 20:25
@junichi11 Thank you so much for your quick help in this! 

@fredw Could you kindly reinstall the plugin with the latest code from github. You may either install the plugin from source or use the precompiled version here: https://github.com/madflow/flow-netbeans-markdown/tree/master/nbm

Please report back if the issue is fixed for you. Thanks!

**Comment by fredw** [comment] 2013-07-27 21:28
Perfect, now it's works.
Thanks!

**Closed as completed** 2013-07-28 16:18 UTC
Labels: Bug
